def handlingErrorsNotes() :
    print('1. A divide-by-zero error happens when Python divides a number by zero.')
    print('2. Errors cause the program to crash. (This doesnt damage your computer at all. Its just that the computer doesnt know how to carry out this instruction, so it immediately stops the program by "crashing" rather than continue.')
    print('3. An error that happens inside a try block will cause code in the except block to execute. That code can handle the error or display a message to the user so that the program can keep going.')


handlingErrorsNotes()